name: 'Package Formatter'
description: 'Format workflow artifact to release packages'
inputs:
    artifact_name:
        required: true
        type: string
    upload_url:
        required: true
        type: string
    commands:
        required: true
        type: string
    access_token:
        required: true
        type: string
outputs:
    artifact_name: 
        description: 'Echo of the input'  
        value: ${{inputs.artifact_name}}

runs:
  using: "composite"
  steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{inputs.artifact_name}}
          path: ${{github.workspace}}/temp
      - name: Zip artifact files
        shell: bash
        working-directory: ${{github.workspace}}/temp
        run: |
          ls -R build
          mv build/* .
          mv base/DoomBFA.sh DoomBFA.sh
          cp -r -u  -f ./BFA_Assets/* .
          rm -r ./BFA_Assets
          rm -r ./base/renderprogs
          mkdir third-party-licenses
          mv vcpkg_installed/x64-linux/share/* third-party-licenses
          chmod +x DoomBFA
          chmod +x DoomBFA.sh
          rm -d -R build
          ${{inputs.commands}}
          zip -m -r ${{inputs.artifact_name}}.zip .
      - name: Upload Artifact to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ inputs.access_token }}
        with:
          upload_url: ${{ inputs.upload_url }}
          asset_path: ${{github.workspace}}/temp/${{inputs.artifact_name}}.zip
          asset_name: ${{inputs.artifact_name}}.zip
          asset_content_type: application/zip
      - name: Delete artifact zip file
        working-directory: ${{github.workspace}}/temp
        shell: bash
        run: rm ${{inputs.artifact_name}}.zip