name: Upload Artifact

on:
    workflow_call:
        inputs:
            artifact_name:
                required: true
                type: string
            executable_path:
                required: true
                type: string
            vcpkg_triplet:
                required: true
                type: string
        outputs:
            artifact_name:

jobs:
    upload_artifact:
        runs-on: ubuntu-latest
        outputs:
            artifact_name: ${{inputs.artifact_name}}
        
        steps:
          - name: Archive production artifacts
            uses: actions/upload-artifact@v3
            with:
              name: ${{inputs.artifact_name}}
              path: |
                ${{inputs.executable_path}}
                ./build/vcpkg_installed/${{inputs.vcpkg_triplet}}/share/*/copyright
                ./base/*
                ./BFA_Assets/*
                ./base_new/*
                ./COPYING.txt
                ./alsoft.ini
                ./README.md
